### ISSUE TITLE
AudioQuake.exe crashes on Windows 10

### ISSUE THREAD

**Issue by Finnboy94** [matatk/agrip#40] opened 2020-02-23 06:17 UTC
When I build with python build.py on Windows 10, the build is completed, but the AudioQuake.exe file in Dist says> Failed to start script AudioQuake.

**Comment by matatk** [comment] 2020-02-24 22:39
Hi @Finnboy94 thanks for your bug report. Oddly I am not getting the same error—I was actually able to follow the current build instructions and can get both the launcher and the game running. This appears to be good news, in that it should be possible to get it working for you, but I'm not currently sure how to debug the built AudioQuake.exe file.

I found that PyInstaller offers a `--debug` option that causes the built exe file to output various infomration when it runs. However, after running PyInstaller manually with this option enabled (`pyinstaller --debug all -y AudioQuake.spec`) the behaaviour of the genereted exe file was not changed, so I must be missing something.

Does the error message you get have any more to it than "Failed to start script AudioQuake"?

**Comment by Finnboy94** [comment] 2020-02-25 08:08
No, the error is just that one sentence. I am using Python 3.8.1. I was unable to build with PyInstaller's normal version, so I downloaded and installed PyInstaller development version and am able to build, but the error persists. It seems that there might be some modules missing or something -- I can attach the Warning txt file when I get back to the computer where the build was done.

**Comment by matatk** [comment] 2020-02-25 11:02
Thanks for the update. I'd be interested to hear about the problems had with using PyInstaller 3.4. I plan to move to the latest Python and PyInstaller soon, too. Currently I'm using Python 3.7.3.

I figured out how to request debugging info for the built AudioQuake.exe: in AudioQuake.spec, if you change the lines `debug=False,` to `debug=True,` and `console=False,` to `console=True,` you can then run `dist\AudioQuake\AudioQuake.exe` in the command prompt and it will output lots of debugging messages. They should identify what the problem is (if you're happy to paste them all in here then great, but they will include the path on your system to the AudioQuake folder, just so you know).

**Comment by Finnboy94** [comment] 2020-02-25 13:48
Actually, after changing Debug=True and Console=True, the program just exits when started from dist. I have attached the warning txt file from Build folder.
[warn-AudioQuake.txt](https://github.com/matatk/agrip/files/4250262/warn-AudioQuake.txt)

**Comment by matatk** [comment] 2020-03-05 11:01
Thanks for your update. When you set `Debug` and `Console` to "True", are you running AudioQuake.exe in the Command Prompt? I would expect it to produce some output even if it crashes.

Thanks for sending the warnings file. Interestingly, the one generated when I run a build is similar but has far fewer things missing, and a cursory glance showed none from the standard library.

When I run the command `python` in a Command Prompt, it tells me that I'm using the 32-bit version of Python—I wonder if you are using the 64-bit one (if so, maybe that's the cause of the issue)?

**Comment by matatk** [comment] 2021-04-02 14:00
Closing this for now, as I can't reproduce it, and hopefully the latest code fixes it. Feel free to re-open if it's still a problem; thanks for your bug report.

**Closed by matatk** 2021-04-02 14:00 UTC
